##  Introduction to numpy
### 1.Numpy : np.array(),ones(),zeros(),eye(),type()

In [1]:
print("Hello World")

Hello World


for jupitor install : pip install numpy
use : import numpy as np

In [2]:
import numpy as np

#### create Numpy Arry

In [5]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
l1 = [5,6,7,8,9,10]
print(l1)
print(type(l1))
a1 = np.array(l1)
print(a1)

[5, 6, 7, 8, 9, 10]
<class 'list'>
[ 5  6  7  8  9 10]


### Multi D List

In [8]:
l1 = [1,2,3,[4,5],[6,7,9]]
l1

[1, 2, 3, [4, 5], [6, 7, 9]]

In [10]:
arr2 = np.array([[1,2,3],[4,5,7],[8,9,10]])
print(arr2)

[[ 1  2  3]
 [ 4  5  7]
 [ 8  9 10]]


In [16]:
# one's Array
one = np.ones((2,3),dtype = int)
print(one)

[[1 1 1]
 [1 1 1]]


In [18]:
zero = np.zeros((2,3),dtype = int)
print(zero)

[[0 0 0]
 [0 0 0]]


In [20]:
identity = np.eye(3,dtype = int)
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
for i in range(1,101):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

In [23]:
arr1 = np.arange(1,101)
arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
arr1 = np.arange(2,101,2)
arr1

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [26]:
for i in range(1,100,2):
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
